language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
before_install:
  - pip install git+git://srobo.org/comp/ranker.git
  - pip install git+git://srobo.org/comp/srcomp.git
install: python setup.py install
script: python setup.py nosetests
